# Generated by Django 4.1.5 on 2023-02-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "남성"), ("W", "여성")],
                max_length=1,
                null=True,
                verbose_name="성별",
            ),
        ),
    ]
