# Generated by Django 4.1.6 on 2023-02-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('남성', '남성'), ('여성', '여성')], max_length=10, null=True, verbose_name='성별'),
        ),
    ]
