# Generated by Django 4.1.5 on 2023-02-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_profile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("남성", "남성"), ("여성", "여성")],
                max_length=10,
                null=True,
                verbose_name="성별",
            ),
        ),
    ]
