# Generated by Django 4.1.6 on 2023-02-13 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talkcomment',
            old_name='talk',
            new_name='post',
        ),
    ]
