# Generated by Django 3.2 on 2023-02-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='category',
            field=models.CharField(choices=[('공동 구매', '공동 구매'), ('오픈런', '오픈런'), ('잡담방', '잡담방')], max_length=10),
        ),
    ]
