# Generated by Django 4.1.6 on 2023-02-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='category',
            field=models.CharField(choices=[('공동 구매', '공동 구매'), ('오픈런', '오픈런'), ('고민방', '고민방')], max_length=5),
        ),
    ]
