# Generated by Django 4.1.6 on 2023-02-07 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='main/images/clothes/%Y/%m/%d')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('buying', models.TextField(blank=True, null=True)),
                ('like', models.ManyToManyField(blank=True, related_name='AccLike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='main/images/clothes/%Y/%m/%d')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('buying', models.TextField(blank=True, null=True)),
                ('like', models.ManyToManyField(blank=True, related_name='BottomLike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='main/images/clothes/%Y/%m/%d')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('buying', models.TextField(blank=True, null=True)),
                ('like', models.ManyToManyField(blank=True, related_name='OutterLike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='main/images/clothes/%Y/%m/%d')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('buying', models.TextField(blank=True, null=True)),
                ('like', models.ManyToManyField(blank=True, related_name='ShoesLike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='main/images/clothes/%Y/%m/%d')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('buying', models.TextField(blank=True, null=True)),
                ('like', models.ManyToManyField(blank=True, related_name='TopLike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='private',
            new_name='open',
        ),
        migrations.RemoveField(
            model_name='post',
            name='clothes',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.AddField(
            model_name='post',
            name='acc',
            field=models.ManyToManyField(blank=True, related_name='Acc', to='main.acc'),
        ),
        migrations.AddField(
            model_name='post',
            name='bottom',
            field=models.ManyToManyField(blank=True, related_name='Bottom', to='main.bottom'),
        ),
        migrations.AddField(
            model_name='post',
            name='outter',
            field=models.ManyToManyField(blank=True, related_name='Outter', to='main.outter'),
        ),
        migrations.AddField(
            model_name='post',
            name='shose',
            field=models.ManyToManyField(blank=True, related_name='Shose', to='main.shose'),
        ),
        migrations.AddField(
            model_name='post',
            name='top',
            field=models.ManyToManyField(blank=True, related_name='Top', to='main.top'),
        ),
    ]
