# Generated by Django 3.2 on 2023-02-07 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='main/images/clothes/%Y/%m/%d')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('buying', models.TextField(blank=True, null=True)),
                ('like', models.ManyToManyField(blank=True, related_name='OuterLike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='outter',
        ),
        migrations.DeleteModel(
            name='Outter',
        ),
        migrations.AddField(
            model_name='post',
            name='outer',
            field=models.ManyToManyField(blank=True, related_name='Outer', to='main.Outer'),
        ),
    ]
