# Generated by Django 4.1.6 on 2023-02-18 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)sLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
