# Generated by Django 3.2 on 2023-02-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='category',
            field=models.CharField(choices=[('buying', '공동 구매'), ('openrun', '오픈런'), ('other', '고민방')], max_length=10),
        ),
    ]
