# Generated by Django 3.2 on 2023-02-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_clothes_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
