# Generated by Django 3.2 on 2023-02-07 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20230207_2119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shose',
            new_name='Shoes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shose',
        ),
        migrations.AddField(
            model_name='post',
            name='shoes',
            field=models.ManyToManyField(blank=True, related_name='Shoes', to='main.Shoes'),
        ),
    ]
