# Generated by Django 3.2 on 2023-02-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_talk_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='rem_img',
            field=models.ImageField(blank=True, null=True, upload_to='main/images/remclothes/%Y/%m/%d'),
        ),
    ]
