# Generated by Django 4.1.6 on 2023-02-13 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_talk_talkcomment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talkcomment',
            old_name='post',
            new_name='talk',
        ),
    ]
